// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nanucdqgyowmkezxuczm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbnVjZHFneW93bWtlenh1Y3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDE2MDAsImV4cCI6MjA2ODUxNzYwMH0.ei1jB2UaPNBBQb_uX31U5pEv17FGXGC3NsmvzvGZ1mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});